---
- name: Current Kernel Version
  shell: uname -r
  register: curr_ker
- name: Intiating Patching
  yum:
      name: kernel
      state: latest
  register: yum_update
- debug: msg="kernel has been updated"
  when: yum_update.rc == 0
- name: check if reboot is required or not
  shell: kernel_new=$(rpm -qa --last kernel | head -1| awk '{print $1}' | sed 's/kernel-//g'); kernel_now=$(uname-r); if [[ $kernel_new != $kernel_now ]]; then echo "reboot is required"; else echo "reboot is not required"; fi
  ignore_errors: true
  register: reboot_check
- debug: msg="{{ reboot_check.stdout }}"
- name: rebooting after patching
  shell: "shutdown -r now"
  async: 1
  poll: 0
- name: wait for the system to come up
  pause:
        minutes: 2
- name: New Kernal Version
  shell: uname -r
  register: new_ker
- debug: msg="New Kernal Version is {{ new_ker.stdout }} and old kernal version was {{ curr_ker.stdout}}"
