---
- name: Verify app server is running or not
  shell: if ps -eaf | grep 'httpd' | grep -v grep > /dev/null; then echo 'process_running' ; else echo 'process_not_running' ; fi
  ignore_errors: true
  register: appr_proc_check
- debug: msg="{{ appr_proc_check.stdout }}"
