---
-
# target where you need to play the playbook
  hosts: db1

  tasks:
    - name: Shutdown Centos System
        command: poweroff
        when: (ansible_os_family == "RedHat" and ansible_distribution_major_version == "6") or (ansible_os_family == "CentOS" and ansible_distribution_major_version == "6.5")
