---
-
# target where you need to play the playbook
  hosts: db1

  vars:
    motd: "welcome to ansible rock" #key value
    motd_ubuntu: "Welcome to ubuntu ansible"
  tasks:
    - name: configure an motd(message of the day)
      copy:
        content: "{{ motd }}"
        dest: /etc/motd
      notify: MOTD Changed
      when: ansible_distribution == 'CentOS'
    - name: configure an motd(message of the day)
      copy:
        content: "{{ motd_ubuntu }}"
        dest: /etc/motd
      notify: MOTD Changed
      when: ansible_distribution == 'Ubuntu'
    - name: Install Epel
      yum:
        name: epel-release
        update_cache: yes
        state: latest
      when: ansible_distribution == 'CentOS'
    - name: Install Apache
      yum:
        name: httpd
        update_cache: yes
        state: latest
      when: ansible_distribution == 'CentOS'
    - name: start apache service
      service:
        name: httpd
        state: restarted
    - name: Install Firewalld 
      yum:
        name: firewalld 
        update_cache: yes
        state: latest
      when: ansible_distribution == 'CentOS'

    - name: open centos firewall
      firewalld:
        service: http
        permanent: true 
        state: enabled
      when: ansible_distribution == 'CentOS'
      notify: Reload Firewalld
  
  handlers:
    - name: MOTD Changed 
      debug:
        msg: The Motd has changed
    - name: Reload Firewalld
      service:
        name: firewalld
        state: reloaded
